Feature/generic request parameters
urielha/log4stash pull request #32
Opened 2017-05-06 07:30 UTC by erangil2

@urielha your wish (part of it at least) has come true.
This branch adds an option to use any parameter you want when sending a request to ElasticSearch.
I removed the RoutingSource parameter as it is redundant after this change.
It also supports the (not-so) old DocumentIdSource for backwards-compatibility.

2017-05-14 11:22 UTC, urielha requested changes
Thanks a lot dude!
We have a little problem that the tests are failing (I think due to line 42 which I comment at)
If you won't get to it and I will find some time to invest in this feature myself, I will correct the things myself.

2017-05-14 11:22 UTC, urielha commented on src/log4stash.Tests/Integration/ElasticSearchAppenderTests.cs
> +                oldDocId = appender.RequestParameters["_id"];
I think this cause the tests to fail. Please use `TryGetValue()` instead

2017-05-14 11:22 UTC, urielha commented on src/log4stash.Tests/Integration/ElasticSearchAppenderTests.cs
> +                if (appender.RequestParameters.ContainsKey("_routing"))
`TryGetValue` here too

2017-05-14 11:22 UTC, urielha commented on src/log4stash/Configuration/RequestParameterDictionary.cs
> +    public class RequestParameterDictionary : IDictionary<string, string>
In my opinion there is no need to implement `IDictionary` here.
You are just "hiding" a regular dictionary.. I think the only function which is needed here is `AddParameter`.

I saw also that you are using `RequestParameters.ToDictionary` (and I think this is the reason you had to implement  IDictionary), instead you can add another instance function to `RequestParameterDictionary` class and this function will return the desired result.

2017-05-14 11:24 UTC, urielha commented
Another thing actually - I prefer to have `LogEventSmartFormatter` as the value (instead of just string)
I will try to do that.

2017-05-17 06:47 UTC, urielha commented on src/log4stash/ElasticClient/InnerBulkOperation.cs
> +        public Dictionary<string, object> RequestParameters { get; set; }
I think the name `IndexOperationParams` is more suitable

2017-05-17 07:06 UTC, urielha requested changes
This should do it for the `SmartFormatter`
Still need to update tests and in my opinion a better name for "RequestParameters" would be "IndexOperationParams"

2017-05-20 08:38 UTC, erangil2 commented
made the rename as requested and fixed the failing tests (had to do with the LogEventSmartFormatter and a NullArgumentExcpetion).
That should do it :)

2017-05-21 07:57 UTC, urielha approved these changes

2017-05-21 07:58 UTC, merged

2017-05-21 07:58 UTC, urielha commented
Thanks!